# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
# Enable version updates for GitHub Actions workflows
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Ignore updates for dependencies with names containing "github-script"
      - dependency-name: "*github-script*"

  # Enable version updates for Docker
  - package-ecosystem: docker
    directory: "./dockerfiles"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/maven"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/multi"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/node"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/python"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/sidekick"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/android"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: "./dockerfiles/golang"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10