name: Run Dependabot

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Dependabot
        uses: dependabot/dependabot-core@v0.288.0
        with:
          package-manager: "github-actions"
          directory: "/"
          target-branch: "main"
          open-pull-requests-limit: 5
