# This is a GitHub Actions workflow named "updatecli"
name: updatecli
on:
  # This workflow can be triggered manually
  workflow_dispatch:
  # This workflow is scheduled to run once per week (to avoid alert fatigue)
  # Specifically, it runs every Monday at 2am UTC
  schedule:
    - cron: '0 2 * * 1'
  # This workflow is also triggered on every push event
  push:
  # This workflow is also triggered on every pull request event
  pull_request:
jobs:
  # This job is named "updatecli"
  updatecli:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository using the checkout action
      - name: Checkout
        uses: actions/checkout@v4

      # This step installs Updatecli in the runner using the updatecli-action
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2.56.0

      # This step runs Updatecli in Dry Run mode
      # It uses the "diff" command of updatecli with the specified config and values files
      # The GitHub token is passed as an environment variable
      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # This step runs Updatecli in Apply mode, but only if the current branch is 'main'
      # It uses the "apply" command of updatecli with the specified config and values files
      # The GitHub token is passed as an environment variable
      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/main'
        run: updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
